/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_synthbot_jasiohost_JAsioHost */

#ifndef _Included_com_synthbot_jasiohost_JAsioHost
#define _Included_com_synthbot_jasiohost_JAsioHost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_synthbot_jasiohost_JAsioHost
 * Method:    loadDriver
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_synthbot_jasiohost_JAsioHost_loadDriver
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_synthbot_jasiohost_JAsioHost
 * Method:    removeCurrentDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_synthbot_jasiohost_JAsioHost_removeCurrentDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_synthbot_jasiohost_JAsioHost
 * Method:    getDriverNames
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_jasiohost_JAsioHost_getDriverNames
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_synthbot_jasiohost_JAsioHost
 * Method:    getCurrentDriverName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_synthbot_jasiohost_JAsioHost_getCurrentDriverName
  (JNIEnv *, jclass);

/*
 * Class:     com_synthbot_jasiohost_JAsioHost
 * Method:    getCurrentDriverIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_synthbot_jasiohost_JAsioHost_getCurrentDriverIndex
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
